#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../../.." && pwd)"
WEB_ENV_FILE="$ROOT_DIR/apps/web/.env.local"
BROADCAST_FILE="$ROOT_DIR/packages/contracts/broadcast/Deploy.s.sol/11155111/run-latest.json"
ADDRESS_INPUT="${1:-}"

if ! command -v bun >/dev/null 2>&1; then
  echo "bun is required. Install bun and re-run."
  exit 1
fi

ADDRESS="$ADDRESS_INPUT"

if [ -z "$ADDRESS" ]; then
  if [ ! -f "$BROADCAST_FILE" ]; then
    echo "No address passed and broadcast file missing: $BROADCAST_FILE"
    echo "Usage: $0 0xYourDeployedAddress"
    exit 1
  fi

  ADDRESS="$(bun --eval "
    const f = process.argv[1];
    const data = await Bun.file(f).json();
    const txs = Array.isArray(data.transactions) ? data.transactions : [];
    const match = txs.find((tx) => tx.contractName === 'ProofRollArena' && tx.contractAddress);
    if (!match) process.exit(2);
    console.log(match.contractAddress);
  " "$BROADCAST_FILE" || true)"

  if [ -z "$ADDRESS" ]; then
    echo "Could not detect ProofRollArena address from broadcast json"
    echo "Usage: $0 0xYourDeployedAddress"
    exit 1
  fi
fi

bun --eval "
  const addr = process.argv[1];
  if (!/^0x[a-fA-F0-9]{40}$/.test(addr)) process.exit(2);
" "$ADDRESS" || {
  echo "Invalid address: $ADDRESS"
  exit 1
}

bash "$ROOT_DIR/packages/contracts/scripts/export-abi.sh"

{
  echo "# Auto-generated by sync-web-artifacts.sh"
  echo "VITE_PROOFROLL_CONTRACT_ADDRESS=$ADDRESS"
} > "$WEB_ENV_FILE"

echo "Synced ABI + contract address"
echo "Address: $ADDRESS"
echo "Env file: $WEB_ENV_FILE"
